name: PremiumFarming
version: 1.0.0
main: ca.pandaaa.premiumfarming.PremiumFarming
api-version: 1.16
commands:
  premiumfarming:
    aliases: [pf, pfarming, farming]
    description: PremiumFarming commands.

premissions:
  premiumfarming.config:
    default: op
    description: ????
